[package]
name = "crater-lang"
version = "0.1.0"
authors = ["dark64 <darko@shardlabs.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"